version: "3.8"

services:
  benchmark:
    image: alpine:latest
    container_name: benchmark-runner
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["/bin/sh", "-c"]
    command: ["chmod +x benchmark.sh && ./benchmark.sh"]
