version: "3.8"

services:
  benchmark:
    image: alpine:latest
    container_name: benchmark-runner
    volumes:
      - .:/host
    working_dir: /host
    command: ["/bin/sh", "-c", "chmod +x benchmark.sh && ./benchmark.sh"]